language: python

python:
  - "2.7"

addons:
  postgresql: "9.3"
# debsources uses 9.4

notifications:
  email: false

before_install:
  - pwd
  - sudo apt-get update -qq
  - sudo apt-get install -y apache2 libapache2-mod-fcgid libapache2-mod-wsgi python-debian python-flask python-flup python-magic tango-icon-theme debmirror exuberant-ctags python-matplotlib python-psycopg2 python-sqlalchemy sloccount python-nose python-flaskext.wtf dpkg-dev
  - mkdir /tmp/python-magic && wget https://raw.githubusercontent.com/file/file/master/python/magic.py -O /tmp/python-magic/magic.py && export PYTHONPATH=/tmp/python-magic/:$PYTHONPATH

# apt's python-magic and pypi's python-magic are different.
# We need the one in apt, and since it's not in pypi, it's installed
# through wget (because Travis uses virtual env without dist-packages).
# Will likely break soon.

# packages missing: libjs-highlight (not in Ubuntu 12.04)

before_script:
  - cp etc/config.travis.ini etc/config.ini
  - sed -i 's?TRAVISWD?'`pwd`'?' etc/config.ini
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/debsources
  - psql -c 'create database debsources;' -U postgres
  - bin/debsources-dbadmin --createdb postgresql://postgres@localhost/debsources
  - bin/debsources-update
  - psql -c "select * from suites, files where files.package_id = suites.package_id and suite = 'jessie';" -U postgres debsources -o coucou && cat coucou

script: make test
