language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y apache2 libapache2-mod-fcgid libapache2-mod-wsgi python-debian python-flask python-flup python-magic tango-icon-theme debmirror exuberant-ctags python-matplotlib python-psycopg2 python-sqlalchemy sloccount python-nose python-flaskext.wtf dpkg-dev
# missing: libjs-highlight (not in Ubuntu 12.04)

before_script:
  - cp etc/config.travis.ini etc/config.ini
  - mkdir /opt/debsources
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/debsources
  - psql -c 'create database debsources;' -U postgres
  - bin/debsources-dbadmin --createdb postgresql://postgres@localhost/debsources
  - bin/debsources-update

addons:
  postgresql: "9.3"
# debsources uses 9.4

script: make test

notifications:
  email: false
